# Generated by Django 5.0.3 on 2024-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people_images/'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instrument_images/'),
        ),
    ]
