# Generated by Django 5.0.3 on 2024-04-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_instruments', '0003_remove_people_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='id_people',
        ),
        migrations.AddField(
            model_name='category',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_instruments.people'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_instruments.category'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
