# Generated by Django 5.0.3 on 2024-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_instruments', '0004_remove_instrument_id_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
